export const protectedPaths = ["/watchlist", "/tasks", "/"];

export const keywords = [
  { id: "1", keyword: "web development company" },
  { id: "2", keyword: "seo companies" },
  { id: "3", keyword: "digital marketing agencies" },
  { id: "4", keyword: "mobile app development company" },
  { id: "5", keyword: "web design companies" },
  { id: "6", keyword: "content marketing agency" },
  { id: "7", keyword: "marketing companies" },
  { id: "8", keyword: "web design company" },
  { id: "9", keyword: "web design design company" },
  { id: "10", keyword: "app development company" },
  { id: "11", keyword: "video production company" },
  { id: "12", keyword: "best seo company" },
  { id: "13", keyword: "social media agency" },
  { id: "14", keyword: "digital marketing agency" },
  { id: "15", keyword: "mobile app developers" },
  { id: "16", keyword: "seo firm" },
  { id: "17", keyword: "search optimization companies" },
  { id: "18", keyword: "best digital marketing agency" },
  { id: "19", keyword: "interior design companies" },
  { id: "20", keyword: "seo optimization agency" },
  { id: "21", keyword: "app development companies" },
  { id: "22", keyword: "app developers" },
  { id: "23", keyword: "seo optimization company" },
  { id: "24", keyword: "graphic design agency" },
  { id: "25", keyword: "mobile application developers" },
  { id: "26", keyword: "search engine optimization agencies" },
  { id: "27", keyword: "best seo agency" },
  { id: "28", keyword: "ppc company" },
  { id: "29", keyword: "social media marketing companies" },
  { id: "30", keyword: "software development companies" },
  { id: "31", keyword: "branding company" },
  { id: "32", keyword: "web design firm" },
  { id: "33", keyword: "small business consulting firms" },
  { id: "34", keyword: "website design firm" },
  { id: "35", keyword: "advertising companies" },
  { id: "36", keyword: "website design companies" },
  { id: "37", keyword: "seo agencies" },
  { id: "38", keyword: "seo optimization companies" },
  { id: "39", keyword: "email marketing companies" },
  { id: "40", keyword: "search engine optimization companies" },
  { id: "41", keyword: "good seo companies" },
  { id: "42", keyword: "best rated seo companies" },
  { id: "43", keyword: "best seo companies" },
  { id: "44", keyword: "video production agency" },
  { id: "45", keyword: "ios app development company" },
  { id: "46", keyword: "web design agency" },
  { id: "47", keyword: "netreputation reviews" },
  { id: "48", keyword: "website design company" },
  { id: "49", keyword: "logo design companies" },
  { id: "50", keyword: "mobile app development agency" },
  { id: "51", keyword: "website design firms" },
  { id: "52", keyword: "social media marketing agencies" },
  { id: "53", keyword: "branding agencies" },
  { id: "54", keyword: "software dev companies" },
  { id: "55", keyword: "web development companies" },
  { id: "56", keyword: "video production companies" },
  { id: "57", keyword: "mobile application development company" },
  { id: "58", keyword: "technical seo agency" },
  { id: "59", keyword: "link building agency" },
  { id: "60", keyword: "design agency" },
  { id: "61", keyword: "local seo agency" },
];

export const master_keywords = [
  { id: "1", keyword: "web development company" },
  { id: "2", keyword: "seo companies" },
  { id: "3", keyword: "digital marketing agencies" },
  { id: "4", keyword: "mobile app development company" },
  { id: "5", keyword: "web design companies" },
  { id: "6", keyword: "content marketing agency" },
  { id: "7", keyword: "marketing companies" },
  { id: "8", keyword: "web design company" },
  { id: "9", keyword: "web design design company" },
  { id: "10", keyword: "app development company" },
  { id: "11", keyword: "video production company" },
  { id: "12", keyword: "best seo company" },
  { id: "13", keyword: "social media agency" },
  { id: "14", keyword: "digital marketing agency" },
  { id: "15", keyword: "mobile app developers" },
  { id: "16", keyword: "seo firm" },
  { id: "17", keyword: "search optimization companies" },
  { id: "35", keyword: "advertising companies" },
  { id: "36", keyword: "website design companies" },
  { id: "37", keyword: "seo agencies" },
  { id: "38", keyword: "seo optimization companies" },
  { id: "39", keyword: "email marketing companies" },
  { id: "40", keyword: "search engine optimization companies" },
  { id: "41", keyword: "good seo companies" },
  { id: "42", keyword: "best rated seo companies" },
  { id: "43", keyword: "best seo companies" },
  { id: "44", keyword: "video production agency" },
  { id: "45", keyword: "ios app development company" },
  { id: "46", keyword: "web design agency" },
  { id: "47", keyword: "netreputation reviews" },
  { id: "58", keyword: "technical seo agency" },
  { id: "59", keyword: "link building agency" },
  { id: "60", keyword: "design agency" },
  { id: "61", keyword: "local seo agency" },
];
